import { v2 as cloudinary } from 'cloudinary';

const VARIANT_WIDTH = { thumb: 480, full: 2048 };
// Formats every browser can play without transcoding.
const NATIVE_VIDEO = new Set(['video/mp4', 'video/webm']);
// Cloudinary files audio under its "video" resource type.
const cloudType = (resourceType) => (resourceType === 'audio' ? 'video' : resourceType);

/**
 * Assets are uploaded with type "authenticated": the original URL is not
 * publicly reachable and every delivery URL must carry a server signature.
 */
export function createCloudinaryStorage({ cloudName, apiKey, apiSecret, folder }) {
  cloudinary.config({ cloud_name: cloudName, api_key: apiKey, api_secret: apiSecret, secure: true });

  const baseOptions = (resourceType) => ({
    resource_type: resourceType,
    type: 'authenticated',
    sign_url: true,
    secure: true,
  });

  return {
    name: 'cloudinary',

    async upload({ filePath, resourceType, mimeType, subfolder }) {
      const options = {
        resource_type: cloudType(resourceType),
        type: 'authenticated',
        folder: subfolder ? `${folder}/${subfolder}` : resourceType === 'audio' ? `${folder}/voice` : `${folder}/${resourceType}s`,
        unique_filename: true,
        use_filename: false,
        overwrite: false,
      };
      if (resourceType === 'video' && !NATIVE_VIDEO.has(mimeType)) {
        // e.g. iPhone .mov: pre-build an MP4 rendition so playback is instant.
        options.eager = [{ format: 'mp4', quality: 'auto', width: 1280, crop: 'limit' }];
        options.eager_async = true;
      }
      const result =
        resourceType === 'video'
          ? await new Promise((resolve, reject) =>
              cloudinary.uploader.upload_large(filePath, { ...options, chunk_size: 20 * 1024 * 1024 }, (err, res) =>
                err ? reject(err) : resolve(res),
              ),
            )
          : await cloudinary.uploader.upload(filePath, options);

      return {
        key: result.public_id,
        width: result.width,
        height: result.height,
        duration: result.duration,
        bytes: result.bytes,
      };
    },

    url(key, { resourceType = 'image', variant = 'full', mimeType, format } = {}) {
      // MP3 plays everywhere, including Safari for Chrome-recorded WebM/Opus.
      // Songs pass their own format: served as uploaded, no transcoding.
      if (resourceType === 'audio') return cloudinary.url(key, { ...baseOptions('video'), format: format || 'mp3' });
      if (resourceType === 'video') {
        const transcode = mimeType && !NATIVE_VIDEO.has(mimeType);
        return cloudinary.url(key, {
          ...baseOptions('video'),
          ...(transcode && { format: 'mp4', transformation: [{ quality: 'auto', width: 1280, crop: 'limit' }] }),
        });
      }
      return cloudinary.url(key, {
        ...baseOptions('image'),
        transformation: [{ width: VARIANT_WIDTH[variant] || VARIANT_WIDTH.full, crop: 'limit', quality: 'auto', fetch_format: 'auto' }],
      });
    },

    /** Poster frame generated by Cloudinary when the client sent no thumbnail. */
    videoPosterUrl(key) {
      return cloudinary.url(key, {
        ...baseOptions('video'),
        format: 'jpg',
        transformation: [{ start_offset: '0', width: VARIANT_WIDTH.thumb, crop: 'limit', quality: 'auto' }],
      });
    },

    /**
     * Every file Duo stored, page by page: { key, resourceType, bytes, createdAt }.
     * (Admin API; songs and voice notes live under Cloudinary's "video" type.)
     */
    async *list() {
      for (const resourceType of ['image', 'video']) {
        let cursor;
        do {
          const page = await cloudinary.api.resources({ type: 'authenticated', resource_type: resourceType, prefix: `${folder}/`, max_results: 500, next_cursor: cursor });
          for (const r of page.resources) yield { key: r.public_id, resourceType, bytes: r.bytes ?? 0, createdAt: new Date(r.created_at) };
          cursor = page.next_cursor;
        } while (cursor);
      }
    },

    async remove(key, resourceType = 'image') {
      await cloudinary.uploader.destroy(key, { resource_type: cloudType(resourceType), type: 'authenticated', invalidate: true });
    },
  };
}
